tasks:
  hello-job:
    runner: razorci/python
    steps:
   
    - checkout    
    - commands:
      - |
       ./sonar_scanar.sh
       sudo chmod +x sonar_scanar.sh
       sonar-scanner \
        -Dsonar.projectKey= python \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://13.233.98.144:9000 \
        -Dsonar.login=bc4c87d4458ba8693212b09e217dcfa29e2bda0e
